name: WordPress Release (SVN)
run-name: Release

on:
  workflow_dispatch:
    inputs:
      new_tag:
        description: 'Enter the new tag version (*.*.*)'
        required: true

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Process
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        run: |
          chmod 777 ./bin/svn_release.sh
          sudo bash ./bin/svn_release.sh ${{ github.event.inputs.new_tag }}
        shell: bash